<a href="https://colab.research.google.com/github/BRAHIMLOUARDI/movie-web-app/blob/main/simplex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy  as np 

In [8]:
def max(row):
  return np.nanmax(row) >0
  

def max_z_index_f(row):

    return np.nanargmax(row)
def min_alfai_index_f(S,max_z_index):
  columme_bivot,bi=S[:,max_z_index],S[:,-1]
  columme_bivot,bi=np.delete(columme_bivot,-1),np.delete(bi,-1)

  alfai=bi/columme_bivot;
  alfai[np.isinf(alfai)]=np.nan

  return np.nanargmin(alfai)
  
S=[
[1,2,1,0,0,0,120],
[1,1,0,1,0,0,100],
[1,0,0,0,1,0,70],
[0,1,0,0,0,1,50],
[20,10,0,0,0,0,0]]
S=np.array(S,dtype=float)


temp=np.copy(S)
while (max(S[-1]) >0 ):
  max_z_index=max_z_index_f(S[-1])
  min_alfai_index=min_alfai_index_f(S,max_z_index)
  pivot =S[min_alfai_index][max_z_index]     
  for i,line in enumerate(temp):
    for j,coef  in enumerate(line): 
      temp[i][j]=coef -((S[i][max_z_index]*S[min_alfai_index][j])/pivot)
      
  temp[min_alfai_index]=S[min_alfai_index]/pivot
  S=np.copy(temp) 
  print(S)


print(S[-1])



[[ 0.0e+00  2.0e+00  1.0e+00  0.0e+00 -1.0e+00  0.0e+00  5.0e+01]
 [ 0.0e+00  1.0e+00  0.0e+00  1.0e+00 -1.0e+00  0.0e+00  3.0e+01]
 [ 1.0e+00  0.0e+00  0.0e+00  0.0e+00  1.0e+00  0.0e+00  7.0e+01]
 [ 0.0e+00  1.0e+00  0.0e+00  0.0e+00  0.0e+00  1.0e+00  5.0e+01]
 [ 0.0e+00  1.0e+01  0.0e+00  0.0e+00 -2.0e+01  0.0e+00 -1.4e+03]]
[[ 0.00e+00  1.00e+00  5.00e-01  0.00e+00 -5.00e-01  0.00e+00  2.50e+01]
 [ 0.00e+00  0.00e+00 -5.00e-01  1.00e+00 -5.00e-01  0.00e+00  5.00e+00]
 [ 1.00e+00  0.00e+00  0.00e+00  0.00e+00  1.00e+00  0.00e+00  7.00e+01]
 [ 0.00e+00  0.00e+00 -5.00e-01  0.00e+00  5.00e-01  1.00e+00  2.50e+01]
 [ 0.00e+00  0.00e+00 -5.00e+00  0.00e+00 -1.50e+01  0.00e+00 -1.65e+03]]
[    0.     0.    -5.     0.   -15.     0. -1650.]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in true_divide
  if sys.path[0] == '':
