<a href="https://colab.research.google.com/github/BRAHIMLOUARDI/movie-web-app/blob/main/simplex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy  as np 

In [62]:
# print(np.array([1,2,3,4,5])/2)
# S=[
# [1,2,1,0,0,0,120],
# [1,1,0,1,0,0,100],
# [1,0,0,0,1,0,70],
# [0,1,0,0,0,1,50],
# [20,10,0,0,0,0,0]]
# S=np.array(S)
# temp=S

# a = np.arange(4).reshape((2,2))
# a=a/0
# a[0][0]=4
# print(a)

# print(np.nanmax(a))
# print(np.max((temp[-1]/0)))
# max_z_index=max_z_index_f(S[-1])
# min_alfi_index=min_alfi_index_f(S,max_z_index)
# pivot =[min_alfi_index][max_z_index]     
# for line,i in enumerate(temp):
#   for coef ,j in enumerate(line): 
#     print(coef)

# print()


numpy_twod_array = np.array([
                [1, 2, 3, 4], 
                [-5, 0, -7, 8], 
                [-9, -10, 11, 12]
            ])
x,y= numpy_twod_array[:, 0],numpy_twod_array[:, 1]
numpy_twod_array[0]=numpy_twod_array[0]/2
print(numpy_twod_array)
# z=x/y
# z[np.isinf(z)]=np.nan
# print(z)
# print(np.nanmin(z))
# print(np.nanargmin(z))



max_value_twod_row = np.amax(numpy_twod_array, axis = 1)
max_value_twod_col = np.amax(numpy_twod_array, axis = 0)
print("Row wise maximum: ", max_value_twod_row)
print("Column wise maximum: ", max_value_twod_col)


[[  0   1   1   2]
 [ -5   0  -7   8]
 [ -9 -10  11  12]]
Row wise maximum:  [ 2  8 12]
Column wise maximum:  [ 0  1 11 12]


In [ ]:
def max(row):
  return np.nanmax(row) >0
  return False

def max_z_index_f(row):
    # print("max_z_index")
    # print(np.nanargmax(row))
    return np.nanargmax(row)
def min_alfi_index_f(S,max_z_index):
  columme_bivot,bi=S[:,max_z_index],S[:,-1]
  columme_bivot,bi=np.delete(columme_bivot,-1),np.delete(bi,-1)
  print("bi",bi,"columme_bivot",columme_bivot)
  alfi=bi/columme_bivot;
  alfi[np.isinf(alfi)]=np.nan
  # print("max_alfi_index")
  # print(alfi)
  # print(np.nanargmin(alfi))
  return np.nanargmin(alfi)
  
S=[
[1,2,1,0,0,0,120],
[1,1,0,1,0,0,100],
[1,0,0,0,1,0,70],
[0,1,0,0,0,1,50],
[20,10,0,0,0,0,0]]
S=np.array(S,dtype=float)


while (max(S[-1]) >0):
  temp=S
  max_z_index=max_z_index_f(S[-1])
  min_alfi_index=min_alfi_index_f(S,max_z_index)
  pivot =[min_alfi_index][max_z_index]     
  for i,line in enumerate(temp):
    for j,coef  in enumerate(line): 
      # print(coef)
      temp[i][j]=coef -((S[i][max_z_index]*S[min_alfi_index][j])/pivot)
  temp[min_alfi_index]=S[min_alfi_index]/pivot
  S=temp 
  print(S)

print(S[-1])

# if faut trainter le cas au le culomme pivot a de zero avant  la division