<a href="https://colab.research.google.com/github/BRAHIMLOUARDI/movie-web-app/blob/main/simplex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy  as np 

In [52]:
def max(row):
  # print("rvr",np.nanmax(row)," row= ",row )
  return np.nanmax(row) 
  

def max_z_index_f(row):
    return np.nanargmax(row)
     
def min_alfai_index_f(S,max_z_index):
  columme_bivot,bi=S[:,max_z_index],S[:,-1]
  columme_bivot,bi=np.delete(columme_bivot,-1),np.delete(bi,-1)
  alfai=bi/columme_bivot;
  alfai[np.isinf(alfai)]=np.nan
  # pour prondre le min positive numbre on remplace les negatife numbre with nan value
  return np.nanargmin(np.where(alfai > 0, alfai, np.nan))

  
S1=[
[1,0,0,1,0,0,0,1000],
[0,1,0,0,1,0,0,500],
[0,0,1,0,0,1,0,1500],
[3,6,2,0,0,0,1,6750],
[4,12,3,0,0,0,0,0]]

S=[
[1,2,1,0,0,0,120],
[1,1,0,1,0,0,100],
[1,0,0,0,1,0,70],
[0,1,0,0,0,1,50],
[20,10,0,0,0,0,0]]
S=np.array(S,dtype=float)
print(S.shape)
k=0
temp=np.copy(S)
while (max(S[-1]) >0  ):
  max_z_index=max_z_index_f(S[-1])
  min_alfai_index=min_alfai_index_f(S,max_z_index)
  pivot =S[min_alfai_index][max_z_index]     
  for i,line in enumerate(temp):
    for j,coef  in enumerate(line): 
      temp[i][j]=coef -((S[i][max_z_index]*S[min_alfai_index][j])/pivot)
      # print(" max_z_index= ",max_z_index," min_alfai_index= ",min_alfai_index," pivot= ",pivot,"i = ",i,"j = ",j," temp[i][j]= ",temp[i][j]," S[i][j]= ",S[i][j]," coef= ",coef," S[i][max_z_index]= ",S[i][max_z_index],"S[min_alfai_index][j] = ",S[min_alfai_index][j]," ((S[i][max_z_index]*S[min_alfai_index][j])/pivot)= ",((S[i][max_z_index]*S[min_alfai_index][j])/pivot))
  temp[min_alfai_index]=S[min_alfai_index]/pivot
  print(S)
  S=np.copy(temp)
  k+=1







(5, 7)
rvr 20.0  row=  [20. 10.  0.  0.  0.  0.  0.]
 f4 =  [[  1.   2.   1.   0.   0.   0. 120.]
 [  1.   1.   0.   1.   0.   0. 100.]
 [  1.   0.   0.   0.   1.   0.  70.]
 [  0.   1.   0.   0.   0.   1.  50.]
 [ 20.  10.   0.   0.   0.   0.   0.]]
rvr 10.0  row=  [    0.    10.     0.     0.   -20.     0. -1400.]
 f4 =  [[ 0.0e+00  2.0e+00  1.0e+00  0.0e+00 -1.0e+00  0.0e+00  5.0e+01]
 [ 0.0e+00  1.0e+00  0.0e+00  1.0e+00 -1.0e+00  0.0e+00  3.0e+01]
 [ 1.0e+00  0.0e+00  0.0e+00  0.0e+00  1.0e+00  0.0e+00  7.0e+01]
 [ 0.0e+00  1.0e+00  0.0e+00  0.0e+00  0.0e+00  1.0e+00  5.0e+01]
 [ 0.0e+00  1.0e+01  0.0e+00  0.0e+00 -2.0e+01  0.0e+00 -1.4e+03]]
rvr 0.0  row=  [    0.     0.    -5.     0.   -15.     0. -1650.]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in true_divide
  if sys.path[0] == '':
