<a href="https://colab.research.google.com/github/BRAHIMLOUARDI/movie-web-app/blob/main/simplex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy  as np 

In [19]:
S1=[
[1,0,0,-0.5,0,0,0,1000],
[0,1,0,0,1,0,0,500],
[0,0,1,0,0,1,0,1500],
[3,6,2,0,0,0,1,6750],
[0,0,-10,0,0,0,0,1200]]
S=np.array(S1,dtype=float)

print(S.transpose())
variables_de_base='variables de base : '
variables_horsbase='variables horsbase : '
S_transposer=S.transpose()
for i,simplex_column in enumerate(S_transposer[0:-1]):
    if 1 in  simplex_column and simplex_column[-1]==0:
         
         variables_de_base+="x" +str(i+1)+ " = " +str(S_transposer[-1][np.where(simplex_column == 1)[0][0]])+" ,"
    else:
       variables_horsbase+=" x"+str(i+1)+" = "+str(simplex_column[-1])+","
print(variables_de_base,variables_horsbase,' z= ',S[-1][-1])
          

[[ 1.00e+00  0.00e+00  0.00e+00  3.00e+00  0.00e+00]
 [ 0.00e+00  1.00e+00  0.00e+00  6.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  1.00e+00  2.00e+00 -1.00e+01]
 [-5.00e-01  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  1.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  1.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  1.00e+00  0.00e+00]
 [ 1.00e+03  5.00e+02  1.50e+03  6.75e+03  1.20e+03]]
variables de base : x1 = 1000.0 ,x2 = 500.0 ,x5 = 500.0 ,x6 = 1500.0 ,x7 = 6750.0 , variables horsbase :  x3 = -10.0, x4 = 0.0,  z=  1200.0


In [ ]:
def max(row):
  # print("rvr",np.nanmax(row)," row= ",row )
  return np.nanmax(row) 
  

def max_z_index_f(row):
    return np.nanargmax(row)
     
def min_alfai_index_f(S,max_z_index):
  columme_bivot,bi=S[:,max_z_index],S[:,-1]
  columme_bivot,bi=np.delete(columme_bivot,-1),np.delete(bi,-1)
  alfai=bi/columme_bivot;
  alfai[np.isinf(alfai)]=np.nan
  # pour prondre le min positive numbre on remplace les negatife numbre with nan value
  return np.nanargmin(np.where(alfai > 0, alfai, np.nan))

  
S1=[
[1,0,0,1,0,0,0,1000],
[0,1,0,0,1,0,0,500],
[0,0,1,0,0,1,0,1500],
[3,6,2,0,0,0,1,6750],
[4,12,3,0,0,0,0,0]]

S=[
[1,2,1,0,0,0,120],
[1,1,0,1,0,0,100],
[1,0,0,0,1,0,70],
[0,1,0,0,0,1,50],
[20,10,0,0,0,0,0]]
S=np.array(S,dtype=float)
print(S.shape)
k=0
temp=np.copy(S)
while (max(S[-1]) >0  ):
  max_z_index=max_z_index_f(S[-1])
  min_alfai_index=min_alfai_index_f(S,max_z_index)
  pivot =S[min_alfai_index][max_z_index]     
  for i,line in enumerate(temp):
    for j,coef  in enumerate(line): 
      temp[i][j]=coef -((S[i][max_z_index]*S[min_alfai_index][j])/pivot)
      # print(" max_z_index= ",max_z_index," min_alfai_index= ",min_alfai_index," pivot= ",pivot,"i = ",i,"j = ",j," temp[i][j]= ",temp[i][j]," S[i][j]= ",S[i][j]," coef= ",coef," S[i][max_z_index]= ",S[i][max_z_index],"S[min_alfai_index][j] = ",S[min_alfai_index][j]," ((S[i][max_z_index]*S[min_alfai_index][j])/pivot)= ",((S[i][max_z_index]*S[min_alfai_index][j])/pivot))
  temp[min_alfai_index]=S[min_alfai_index]/pivot
  print(S)
  S=np.copy(temp)
  k+=1





